import type { Metadata } from "next";
import { BadgeCheck, Building2, HeartHandshake, Lightbulb, MapPin, ShieldCheck } from "lucide-react";
import { Eyebrow, FinalCta, PageHero } from "@/components/sections";

export const metadata: Metadata = { title: "About", description: "Learn why OffSay is building a better connection between local customers and local businesses." };

export default function AboutPage() {
  return <><PageHero eyebrow="About OffSay" title="Local value deserves to be visible." description="We’re building OffSay to make useful nearby offers easier to discover and local business marketing easier to understand." />
    <section className="section shell story-grid"><div><Eyebrow>Why we exist</Eyebrow><h2>Local offers are everywhere. Finding the right one should not be difficult.</h2></div><div><p>Customers often discover offers too late, without clear terms, or far from where they live. At the same time, local businesses need a simpler way to reach nearby customers and understand what actually creates interest.</p><p>OffSay brings those needs together: location-aware discovery for customers and a focused campaign workspace for merchants.</p></div></section>
    <section className="section soft-section"><div className="shell"><div className="section-heading centered"><Eyebrow>Our principles</Eyebrow><h2>What guides the product.</h2></div><div className="values-grid"><article><MapPin /><h3>Local relevance</h3><p>Start with the user’s location and show what is genuinely nearby.</p></article><article><BadgeCheck /><h3>Clear information</h3><p>Make offer value, validity, terms, and store details easy to understand.</p></article><article><ShieldCheck /><h3>Trust by design</h3><p>Separate verified businesses and OffSay-verified platform offers clearly.</p></article><article><Building2 /><h3>Merchant independence</h3><p>Give businesses practical tools to manage stores and campaigns themselves.</p></article><article><Lightbulb /><h3>Useful insight</h3><p>Focus analytics on actions merchants can understand and improve.</p></article><article><HeartHandshake /><h3>Community value</h3><p>Help customers save locally while helping nearby businesses grow.</p></article></div></div></section>
    <section className="section shell impact-panel"><div><Eyebrow>Our direction</Eyebrow><h2>Build a stronger local discovery layer, one district at a time.</h2><p>OffSay is beginning with a focused experience and growing carefully around real customer and merchant needs.</p></div><div className="impact-stats"><span><strong>Nearby</strong><small>Location-first discovery</small></span><span><strong>Verified</strong><small>Clear trust signals</small></span><span><strong>Measurable</strong><small>Actionable merchant insights</small></span></div></section><FinalCta /></>;
}
