import type { Metadata } from "next";
import { Bookmark, Compass, Heart, Map, MapPin, Search, Share2, SlidersHorizontal, Star } from "lucide-react";
import { AppCta, Eyebrow, FinalCta, PageHero } from "@/components/sections";

export const metadata: Metadata = { title: "How it works", description: "See how OffSay makes nearby offers easier to discover, understand, save, and visit." };

export default function HowItWorksPage() {
  return <>
    <PageHero eyebrow="How OffSay works" title="Local discovery that starts with where you are." description="OffSay brings nearby stores and current offers into a clear experience designed around distance, relevance, and trust." />
    <section className="section shell"><div className="journey"><article><div className="journey-art"><MapPin /><span>Changanassery, Kerala</span><small>Within 20 km</small></div><div><Eyebrow>Step 1</Eyebrow><h2>Choose your location and distance.</h2><p>Use your current position, choose a suggested area, or search for a custom location. Set how far you want to explore.</p><ul className="check-list"><li><SlidersHorizontal /> Adjustable nearby distance</li><li><Map /> District-first browsing</li><li><Compass /> Cached last location when GPS is unavailable</li></ul></div></article><article className="reverse"><div className="journey-art offer-stack"><span><strong>30% OFF</strong><small>Dinner combo</small></span><span><strong>1 + 1</strong><small>Signature mocktails</small></span><span><strong>40% OFF</strong><small>Fresh styles</small></span></div><div><Eyebrow>Step 2</Eyebrow><h2>Discover offers that fit.</h2><p>Browse nearby or explore by district and category. Trending, most-liked, and ending-soon views help you decide faster.</p><ul className="check-list"><li><Search /> Search stores and offers</li><li><Star /> Featured and trending discovery</li><li><Heart /> Community likes and ratings</li></ul></div></article><article><div className="journey-art action-grid"><span><Bookmark />Save</span><span><Heart />Like</span><span><Share2 />Share</span><span><MapPin />Directions</span></div><div><Eyebrow>Step 3</Eyebrow><h2>Save, share, and visit.</h2><p>Open the full terms, check participating stores, contact the business when available, or start directions in Google Maps.</p><ul className="check-list"><li><Bookmark /> Saved offers stay easy to revisit</li><li><Share2 /> Share offer details with friends</li><li><MapPin /> Navigate to the nearest participating store</li></ul></div></article></div></section>
    <section className="section soft-section"><div className="shell faq-layout"><div><Eyebrow>Designed for clarity</Eyebrow><h2>Know before you go.</h2><p>Every offer page brings together the important information in one place.</p></div><div className="feature-list"><span>Offer value and type</span><span>Start and end dates</span><span>Terms and conditions</span><span>Store contact and facilities</span><span>Directions and participating branches</span><span>Customer reviews and ratings</span></div></div></section>
    <section className="section shell narrow"><AppCta /></section><FinalCta />
  </>;
}
