import type { Metadata } from "next";
import { PageHero } from "@/components/sections";
import { siteConfig } from "@/lib/site";

export const metadata: Metadata = { title: "Privacy policy", description: "Read how OffSay handles personal information across its customer and merchant experiences." };

export default function PrivacyPage() {
  return <><PageHero eyebrow="Legal" title="Privacy policy" description="How OffSay collects, uses, and protects information across our customer app, website, and merchant services." /><article className="legal shell narrow"><p className="legal-date">Last updated: 28 July 2026</p><h2>1. Information we collect</h2><p>Depending on how you use OffSay, we may collect your name, email address, phone number, authentication information, approximate or precise location when permitted, saved and liked offers, reviews, device information, and usage activity.</p><p>For merchant services, we also process business, store, branch, contact, location, subscription, team, offer, and analytics information supplied through the merchant workspace.</p><h2>2. How we use information</h2><p>We use information to operate accounts, provide nearby results, personalize discovery, process merchant applications, publish offers, maintain platform safety, provide analytics, respond to support requests, and improve OffSay.</p><h2>3. Location information</h2><p>Location helps OffSay calculate distance and show relevant offers or stores. Where supported, the app may retain a recent location on your device so it can continue showing useful results if location services are unavailable. You can change location permissions in your device settings.</p><h2>4. Sharing and service providers</h2><p>We do not sell personal information. We may share necessary information with infrastructure, authentication, email, maps, analytics, security, or support providers that help us operate the service, or when disclosure is required by law.</p><h2>5. Public content</h2><p>Reviews, ratings, merchant profiles, store information, and published offers may be visible to other users. Do not include sensitive personal information in public content.</p><h2>6. Data retention and security</h2><p>We retain information only as long as reasonably required for the purposes described here, legal obligations, dispute resolution, and platform integrity. We use reasonable technical and organizational safeguards, but no online service can guarantee absolute security.</p><h2>7. Your choices</h2><p>You may update account information, manage location permission, remove saved or liked content, or ask about access, correction, or deletion where applicable. Some records may be retained when required for security, fraud prevention, or legal compliance.</p><h2>8. Children’s privacy</h2><p>OffSay is not directed to children who are not legally able to consent to the processing of personal information in their region.</p><h2>9. Changes to this policy</h2><p>We may update this policy as OffSay evolves. We will publish the updated date and provide additional notice when required.</p><h2>10. Contact</h2><p>For privacy questions, email <a href={`mailto:${siteConfig.contactEmail}`}>{siteConfig.contactEmail}</a>.</p></article></>;
}
